export const APIConfig = {
  RAZORPAY_SECRET:'iPcqI8cJj0nVQAPfEdzJqnb3',
  RAZORPAY_KEY_ID:'rzp_test_HAF6HCcH7moc64',
  APILOCALURL: 'https://localhost:7085/api/',
  APISERVERURL: 'https://hydroidgas.azurewebsites.net/api/',
  APIACTIVATEURL: 'https://hydroidgas.azurewebsites.net/api/',
  LOCALWEBURL:'http://localhost:3000/',
  DEVWEBURL:'http://hydroidgas.developerscode.com/',
  DOMAINACTIVATEURL: 'http://localhost:3000/',

  GETALLGASPRICE: 'GasPrice',
  CREATEGASPRICE: 'GasPrice',
  UPDATEGASPRICE: 'GasPrice',
  DELETEGASPRICE: 'GasPrice',
  GETGASPRICEBYID: 'GasPrice/GetById',

  GETALLCONTACT: 'Contact/Get',
  CREATECONTACT: 'Contact',
  UPDATECONTACT: 'Contact',
  GETCONTACTBYDEALER: 'Contact/GetByDealer',

  GETALLROLES: 'Roles',
  CREATEROLE: 'Roles',
  UPDATEROLE: 'Roles',
  DELETEROLE: 'Roles',
  GETROLEBYID: 'Roles/GetById',

  GETALLUSERS: 'Users',
  GETALLCUSTOMERS: 'Users/GetCustomers',
  GETALLADMINS: 'Users/GetAdmins',
  CREATEUSER: 'Users/CreateUser',
  LOGINUSER: 'Users/Login',
  CHANGEPASSWORD: 'Users/ChangePassword',
  GETUSERBYID: 'Users/GetById',
  DELETEUSER: 'Users',
  USERSTATUS: 'Users/Status',
  USERPROFILE: 'Users/Profile',
  GETCOUNTSDEVICEDATA :'Users/GetAdminCount',

  GETALLDEVICES: 'Devices',
  CREATEDEVICE: 'Devices',
  UPDATEDEVICE: 'Devices',
  DELETEDEVICE: 'Devices',
  GETDEVICEBYID: 'Devices/GetById',

  GETALLGASUSAGE: 'GasUsage/GetMeterReading',
  GETDEVICEDATABYID: 'GasUsage/GetById',
  GETDEVICEDATABYDEVICE: 'GasUsage/Devices/GetByDevice',
  GETBARGRAPHDEVICEDATA :'GasUsage/GetBarGraphData',
  //GETGASUSAGECOUNT :'DevicesData/GetGasUsageCount',  
  GETGASUSAGEBYUSER :'GasUsage/GetMeterReadingByuser',

  GETALLTICKETS: 'Ticket',
  CREATETICKET: 'Ticket',
  UPDATETICKET: 'Ticket',
  DELETETICKET: 'Ticket',
  CLOSETICKET: 'Ticket/Close',
  GETTICKETBYID: 'Ticket',
  GETTICKETBYCATEGORY: 'Ticket/GetByCategory',
  GETTICKETBYUSER: 'Ticket/GetByUser',
  GETTICKETBYSTATUS: 'Ticket/GetByStatus',

  GETALLTICKETCATEGORIES: 'TicketCategory',

  GETALLTICKETRESPONSES: 'TicketResponse',
  CREATETICKETRESPONSE: 'TicketResponse',
  UPDATEDTICKETRESPONSE: 'TicketResponse',
  DELETETICKETRESPONSE: 'TicketResponse',
  GETTICKETRESPONSEBYID: 'TicketResponse/GetByTicketId',

  GETALLTRANSACTIONS: 'Transaction',
  CREATETRANSACTION: 'Transaction',
  GETTRANSACTIONBYUSERID: 'Transaction',
  TODAYSTRANSANCTION: 'Transaction/GetTodaysTotal',

  GETALLORGANISATIONS: 'Organisation',
  CREATEORGANISATION: 'Organisation',
  UPDATEORGANISATION: 'Organisation',
  DELETEORGANISATION: 'Organisation',
  GETORGANISATIONBYID: 'Organisation',

  GETALLAPARTMENTS: 'Apartment',
  CREATEAPARTMENT: 'Apartment',
  UPDATEAPARTMENT: 'Apartment',
  DELETEAPARTMENT: 'Apartment',
  GETAPARTMENTBYID: 'Apartment',

  GETALLBLOCKS: 'Block',
  CREATEBLOCK: 'Block',
  UPDATEBLOCK: 'Block',
  DELETEBLOCK: 'Block',
  GETBLOCKBYID: 'Block',

  GETALLFLOORS: 'Floor',
  CREATEFLOOR: 'Floor',
  UPDATEFLOOR: 'Floor',
  DELETEFLOOR: 'Floor',
  GETFLOORBYID: 'Floor',

  GETALLUNITS: 'Unit',
  CREATEUNIT: 'Unit',
  UPDATEUNIT: 'Unit',
  DELETEUNIT: 'Unit',
  GETUNITBYID: 'Unit',

  GETALLMESSAGES: 'Message',
  CREATEMESSAGE: 'Message',
  UPDATEMESSAGE: 'Message',
  DELETEMESSAGE: 'Message',
  GETMESSAGEBYID: 'Message/GetById',
  GETDISPLAYMESSAGE:'Message/GetDisplayMessage',

  GETALLNOTIFICATIONS: 'Notification',
  CREATENOTIFICATION: 'Notification',
  UPDATENOTIFICATION: 'Notification',
  DELETENOTIFICATION: 'Notification',
  GETNOTIFICATIONBYID: 'Notification',
  GETNOTIFICATIONUNREAD: 'Notification/unread',
  GETNOTIFICATIONREAD: 'Notification/read',
  GETNOTIFICATIONBYUSER: 'Notification/GetByUser',

  GETALLPAYMENTREQUESTS: 'Payment',
  CREATEPAYMENTREQUEST: 'Payment',
  UPDATEPAYMENTREQUEST: 'Payment',
  CANCELPAYMENTREQUEST: 'Payment/CancelPayment',
  GETNPAYMENTREQUESTBYID: 'Payment/GetById',
  GETPAYMENTREQUESTBYUSER: 'Payment/GetByUser',
  PROCESSPAYMENTORDER: 'Payment/ProcessRequestOrder',

  GETGASUSAGECOUNT: 'GasUsage/GetGasUsageCount',
  GETUSERGASUSAGECOUNT: 'GasUsage/GetUserGasUsageCount',
  GETBARGRAPHDATA: 'GasUsage/GetBarGraphData',
  GETUSERBARGRAPHDATA: 'GasUsage/GetUserBarGraphData',
  GETLEAKDATA: 'GasUsage/GetLeakInformation',
  GETBARGRAPHDATEWISE: 'GasUsage/GetBarGraphDateWise',
  GETUSERBARGRAPHDATEWISE: 'GasUsage/GetUserBarGraphDateWise',
  GETMETERDATABYUSER :'GasUsage/GetMeterReadingByuser',

  GETALLGASPRICES: 'GasPrice',
  CREATEGASPRICE: 'GasPrice',
  UPDATEGASPRICE: 'GasPrice',
  DELETEGASPRICE: 'GasPrice',
  GETGASPRICEBYID: 'GasPrice',
  GETLATESTGASPRICE:'GasPrice/Latest'
}